# Generated by Django 4.0.1 on 2022-01-15 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('admission_id', models.AutoField(primary_key=True, serialize=False)),
                ('marks', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Catgory',
            fields=[
                ('catgory_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_nam', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('cours_name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.admission')),
                ('catgory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.catgory')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_tittle', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=255)),
                ('book_edition', models.CharField(max_length=255)),
                ('book_year', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('leader', models.CharField(default='1', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ugroup_learder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=255)),
                ('priority', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Univerisity',
            fields=[
                ('university_id', models.AutoField(primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=255)),
                ('total_coursers', models.BigIntegerField()),
                ('no_lectures', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('us_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('msg', models.TextField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.ugroup')),
            ],
        ),
        migrations.CreateModel(
            name='Univ_cours',
            fields=[
                ('univ_course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.IntegerField()),
                ('university_id', models.IntegerField()),
                ('uni_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.course')),
            ],
        ),
        migrations.CreateModel(
            name='Ugr_usr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.ugroup_learder')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('tchnology_id', models.AutoField(primary_key=True, serialize=False)),
                ('tchnology_name', models.CharField(max_length=255)),
                ('learning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.learning')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=255)),
                ('class_lvl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.level')),
            ],
        ),
        migrations.CreateModel(
            name='Post_message',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('tittle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('time_post', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Other_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('bod', models.CharField(max_length=255)),
                ('gender', models.BigIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('phon_no', models.BigIntegerField()),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='learning',
            name='Material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.material'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.FileField(null=True, upload_to='images/', verbose_name='')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Field_technology',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.field')),
                ('Technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.technology')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.field'),
        ),
        migrations.AddField(
            model_name='admission',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.subject'),
        ),
    ]
